"""Initial Migration

Revision ID: 70d04d84a85b
Revises: 8af46968d7f5
Create Date: 2019-02-13 19:05:42.463847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d04d84a85b'
down_revision = '8af46968d7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitchies', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitchies', 'categories', ['category_id'], ['id'])
    op.add_column('roles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    op.drop_constraint(None, 'pitchies', type_='foreignkey')
    op.drop_column('pitchies', 'category_id')
    # ### end Alembic commands ###
