"""Initial Migration

Revision ID: 70eb2db1ccea
Revises: 70d04d84a85b
Create Date: 2019-02-14 11:55:04.390053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70eb2db1ccea'
down_revision = '70d04d84a85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogs_post'), 'blogs', ['post'], unique=False)
    op.create_index(op.f('ix_blogs_title'), 'blogs', ['title'], unique=False)
    op.drop_index('ix_pitchies_post', table_name='pitchies')
    op.drop_index('ix_pitchies_title', table_name='pitchies')
    op.drop_table('pitchies')
    op.add_column('comments', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.drop_constraint('comments_pitchie_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'blogs', ['blog_id'], ['id'])
    op.drop_column('comments', 'pitchie_id')
    op.drop_constraint('roles_user_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_user_id_fkey', 'roles', 'users', ['user_id'], ['id'])
    op.add_column('comments', sa.Column('pitchie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_pitchie_id_fkey', 'comments', 'pitchies', ['pitchie_id'], ['id'])
    op.drop_column('comments', 'blog_id')
    op.create_table('pitchies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='pitchies_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pitchies_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pitchies_pkey')
    )
    op.create_index('ix_pitchies_title', 'pitchies', ['title'], unique=False)
    op.create_index('ix_pitchies_post', 'pitchies', ['post'], unique=False)
    op.drop_index(op.f('ix_blogs_title'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_post'), table_name='blogs')
    op.drop_table('blogs')
    # ### end Alembic commands ###
